### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [Daniil1380/JavaClassQuaternion#1]
1. Хотелось бы больше тестов. Не хватает тестов, покрывающих граничные и ошибочные случаи.
2. Практически везде (кроме взятия модуля) вы сравниваете double на точное равенство в тестах. Определите в тестах вспомогательный `assertEquals` для кватернионов, принимающий точность сравнения (лучше всего измеряемую в `Math.ulp` для конкретного числа).
3. https://github.com/Daniil1380/JavaClassQuaternion/blob/2a68e7eb1d87b505b042140d50b89d3638ec9625/src/main/java/Quaternion.java#L90-L104

Ненужный боксинг примитивных типов. Постарайтесь понять чем отличается `Double` от `double` в джаве и использовать тот, который нужен.
4. https://github.com/Daniil1380/JavaClassQuaternion/blob/2a68e7eb1d87b505b042140d50b89d3638ec9625/src/main/java/Quaternion.java#L64

Создаёте лишний объект (`new Quaternion(s, i, j, k)`) равный this. 

5. https://github.com/Daniil1380/JavaClassQuaternion/blob/2a68e7eb1d87b505b042140d50b89d3638ec9625/src/main/java/Quaternion.java#L51-L57

лучше написать так:

```java
    Quaternion multi(Quaternion second) {
        double newS = (s * second.s - i * second.i - j * second.j - k * second.k);
        double newI = (s * second.i + second.s * i + j * second.k - k * second.j);
        double newJ = (s * second.j + j * second.s + k * second.i - i * second.k);
        double newK = (s * second.k + k * second.s + i * second.j - j * second.i);
        return new Quaternion(newS, newI, newJ, newK);
    }
```

В таком случае вам не придётся инициализировать кватернион "случайными" значениями перед присваиванием компонентов.

6. https://github.com/Daniil1380/JavaClassQuaternion/blob/2a68e7eb1d87b505b042140d50b89d3638ec9625/src/main/java/Quaternion.java#L65

Косяк в форматировании

**Comment by gagarski** [comment]
7. Немного странным кажется назначение класса `Decart`. По стуи, это альтернативное представление кватерниона, с которым нельзя делать никаких арифметических операций. Я бы посоветовал выделить класс `Vector`, а утилиты оформить в следующем виде (методы класса `Quaternion`):
```java
public double getAngle() { ... }
public Vector getAxis() { ... }
public static Quaternion fromAngleAndAxis(double angle, Vector axis) {
    // ... 
    return new Quaternion(...)
}
```

**Comment by Daniil1380** [comment]
Закройте, пожалуйста, issue) Спасибо

**Comment by gagarski** [comment]
Ещё чуть-чуть:

1. Поправьте типы возвращаемого значения в `getScalar` и `getVector` (аналогично `getAxis` и `getAngle`).
2. `NumberFormatException ` - не самое подходящее по смыслу исключение при делении на ноль (см. Javadoc к нему). Здесь более подходящими по смыслу являются `IllegalArgumentException`, либо `ArithmeticException`.

**Comment by Daniil1380** [comment]
Понял, сейчас исправлю, по второму заданию можно будет завтра вопрос задать? Вроде как базу набросал, хочу утоянить в правильном ли направлении двигаюсь)

**Comment by gagarski** [comment]
Естественно, можно.

**Comment by Daniil1380** [comment]
Кирилл Алексеевич, извините, что тут спрашиваю. Вопрос по 2 заданию возник, Необходимо мне разделить файл посимвольно, но возникает проблема с "\n", как мне ее обрабатывать? У меня получается, если мой reader встречает конец строки, он считает это как два символа, безусловно, я могу не учитывать каждый раз, когда встречаю по отдельности \ и n, но тогда текст из букв n просто не обработается верно. Можно, конечно, придумать что-то из разряда "Если до этого был \, а сейчас n - то от счетчика символов отнимай 2, но тогда возникает не меньше проблем. Вообщем, интересно, каким образом это можно обработать, или просто "забить"? Ведь технически он все таки правильное количество символов запихивает в файл) Спасибо

**Comment by Daniil1380** [comment]
Попробовал '\n' не считать, но не помогает совсем(

**Comment by gagarski** [comment]
Здравствуйте. '\n' - это не два символа `\` и `n`. Это один символ, в джаве обозначающийся таким хитрым образом. Проверьте ещё раз, что считывает ваш `Reader`. Пока не верю, что всё так, как вы говорите. Если вы уверены, что это так, то продемонстрируйте вживую на занятии.

**Comment by Daniil1380** [comment]
Спасибо, проблема решилась подобным образом 

> if (charInInt != 13 && charInInt != 10) i++;
(Тут charInInt - интовое отображение кодировки символа)

10 - есть символ \n, а 13 в таблице Юникод звучит как "Третий код управления устройством (терминалы)".
UPD: символ номер 13 - возврат каретки
Если прописать только 10 или только 13 баг сохраняется, а так все работает

P.S символ номер 13 выловил только благодаря дебагеру, проходя при переходе с одной строки на другую

**Comment by Daniil1380** [comment]
Допилил второе задание, буду рад, если проверите, пока код не особо "красивый", спасибо)
https://github.com/Daniil1380/Spliter
